baseURL = 'debaetsd.github.io'
languageCode = 'en-us'
DefaultContentLanguage = "en" 
title = "Dieter's Blog"
theme = 'holy'
disableKinds = ['taxonomy', 'term']
author = "Dieter De Baets"

[params.author]
name = 'Dieter De Baets'

[params]
copyright = '©Dieter De Baets' 
description = "Graphcis programming ramblings by Dieter De Baets"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10


[privacy]
[privacy.disqus]
    disable = true
[privacy.googleAnalytics]
    disable = true
[privacy.instagram]
    disable = true
[privacy.twitter]
    disable = true
[privacy.vimeo]
    disable = true
[privacy.youtube]
    disable = true

[languages.en.params]
  date_format = "02 Jan 2006"